name: Test Debug
on:
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  unitTest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '18'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run:  chmod +x ./gradlew

      - name: Unit Tests Android
        run: ./gradlew testDebugUnitTest