name: On Pull request opened
on:
  push:
    branches: [ master ]

jobs:
  lint:
    name: Lint Debug Variant
    uses: ./github/workflows/job_lint_debug.yml

  test:
    name: Test Debug Variant
    uses: ./github/workflows/job_test_debug.yml